/**
 * Carrier types generated by a custom split.
 *
 * A split cut to a device's measured width matches no shipped carrier, so a
 * type is generated for it. The slug fingerprints the split, not the carrier,
 * so two rows cut the same way share one type and merging two files does not
 * duplicate it. Editing one carrier's gaps produces a different fingerprint,
 * which is the copy-on-write: the other carriers keep the type they had.
 */

import type { DeviceType, Rack, Slot } from "$lib/types";
import { CATEGORY_COLOURS } from "$lib/types/constants";
import { getRackOpeningMm } from "./device-width";

/** One cell of a generated carrier. */
export interface CarrierCell {
  widthFraction: number;
  heightUnits: number;
}

/** Decimal places the fingerprint rounds to, so float noise cannot fork it. */
const FINGERPRINT_PRECISION = 6;

/**
 * FNV-1a over the canonical split description. A hash keeps the slug short
 * and fixed-length however many cells the row holds; it is a dedup key, not a
 * security primitive.
 */
function fingerprint(input: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(36).padStart(7, "0");
}

/**
 * The slug a split resolves to. Deterministic: the same cells, heights and
 * gaps always give the same slug.
 *
 * @param uHeight - Rail height of the carrier in U
 * @param cells - The cells, left to right
 * @param gapsMm - The n - 1 gaps between them, in millimetres
 */
export function customCarrierSlug(
  uHeight: number,
  cells: CarrierCell[],
  gapsMm: number[],
): string {
  const round = (n: number) => n.toFixed(FINGERPRINT_PRECISION);
  const canonical = [
    round(uHeight),
    cells
      .map((c) => `${round(c.widthFraction)}x${round(c.heightUnits)}`)
      .join(","),
    gapsMm.map(round).join(","),
  ].join("|");
  return `carrier-${uHeight}u-custom-${fingerprint(canonical)}`;
}

/**
 * Build the generated carrier type for a split.
 *
 * @param uHeight - Rail height of the carrier in U
 * @param cells - The cells, left to right
 * @param gapsMm - The n - 1 gaps between them, in millimetres
 */
export function buildCustomCarrierType(
  uHeight: number,
  cells: CarrierCell[],
  gapsMm: number[],
): DeviceType {
  const slots: Slot[] = cells.map((cell, index) => ({
    id: `col-${index + 1}`,
    name: `Column ${index + 1}`,
    position: { row: 0, col: index },
    width_fraction: cell.widthFraction,
    height_units: cell.heightUnits,
  }));

  return {
    slug: customCarrierSlug(uHeight, cells, gapsMm),
    model: `Carrier (${uHeight}U, custom)`,
    u_height: uHeight,
    category: "shelf",
    colour: CATEGORY_COLOURS.shelf,
    subdevice_role: "parent",
    auto_created: true,
    slots,
    slot_gaps: gapsMm,
  };
}

/**
 * Rail height of a generated carrier: the whole U that holds its tallest
 * cell, at least 1U. Rails register whole U only, so a device 4.5U tall gets a
 * 5U carrier and sits in it at its own height.
 *
 * @param cells - The carrier's cells
 */
export function carrierUHeight(cells: CarrierCell[]): number {
  return Math.max(1, ...cells.map((cell) => Math.ceil(cell.heightUnits)));
}

/**
 * The cell a device needs: its measured width over the rack opening, or a
 * half cell when it only carries the half-width descriptor.
 *
 * @param deviceType - The device being given a cell
 * @param rackWidth - Nominal rack width in inches
 */
export function cellForDevice(
  deviceType: DeviceType,
  rackWidth: number,
): CarrierCell {
  let widthFraction: number;
  if (deviceType.width_mm !== undefined) {
    widthFraction = deviceType.width_mm / getRackOpeningMm(rackWidth);
  } else {
    widthFraction = (deviceType.slot_width ?? 2) === 1 ? 0.5 : 1.0;
  }
  return { widthFraction, heightUnits: deviceType.u_height };
}

/**
 * The shape customCarrierSlug produces. Useful where only a slug is in hand,
 * or where reading the flag would be the wrong kind of read: on a Svelte
 * $state proxy, touching a key most types lack subscribes the reader to it.
 */
export const CUSTOM_CARRIER_SLUG_PATTERN = /^carrier-\d+u-custom-[0-9a-z]+$/;

/**
 * Whether a type was generated by a split rather than authored in a library.
 */
export function isGeneratedCarrier(deviceType: DeviceType): boolean {
  return deviceType.auto_created === true;
}

/**
 * Generated types no placed carrier references any more, so the file's
 * library does not grow without bound.
 *
 * @param deviceTypes - The layout's device types
 * @param racks - Every rack in the layout
 * @returns Slugs safe to drop
 */
export function orphanGeneratedTypes(
  deviceTypes: DeviceType[],
  racks: Rack[],
): string[] {
  const inUse = new Set(
    racks.flatMap((rack) => rack.devices.map((d) => d.device_type)),
  );
  return deviceTypes
    .filter((dt) => isGeneratedCarrier(dt) && !inUse.has(dt.slug))
    .map((dt) => dt.slug);
}

/**
 * Whether a generated type should be collected once `carrierId` stops using
 * it. A retype leaves the old split behind: growing a carrier from one cell
 * to four otherwise strands three types in the file's library.
 *
 * @param racks - Every rack in the layout
 * @param slug - The generated type being left behind
 * @param carrierId - The placed carrier that is moving off it
 */
export function isOrphanedAfterRetype(
  racks: Rack[],
  slug: string,
  carrierId: string,
): boolean {
  return !racks.some((rack) =>
    rack.devices.some((d) => d.id !== carrierId && d.device_type === slug),
  );
}
